// angular2/src/app/components/articleDescription/articleDescription.component.ts
import { Component, Input } from '@angular/core';
import { Article } from './../../services/article'
@Component({
  selector: 'articleDescription',
  templateUrl: './articleDescription.component.html',
  styleUrls: ['./articleDescription.component.scss']
})
export class ArticleDescriptionComponent {
  @Input() article: Article;
}
<div>
    <h2>
        <a [routerLink]="['/articles', article.articleId]">{{article.title}}</a>
    </h2>
    <p>
        <span class="glyphicon glyphicon-user"></span> by <strong>{{article.username}}</strong>
        <span class="glyphicon glyphicon-time"></span> Posted on <strong>{{article.datePublication}}</strong>
    </p>

    <hr>
    <img class="img-responsive" [src]="article.picture" />
    <hr>

    <p>{{article.content | slice:0:300}}...</p>
    <a class="btn btn-primary" [routerLink]="['/articles', article.articleId]">Read More <span class="glyphicon glyphicon-chevron-right"></span></a>

    <hr>
</div>

// vue.js/src/components/ArticleDescription.vue
<template>
  <div>

    <h2><a href="#">{{content.title}}</a></h2>
    <p><span class="glyphicon glyphicon-user"></span> by <strong>{{content.username}}</strong></p>
    <p><span class="glyphicon glyphicon-time"></span> Posted on <strong>{{content.datePublication}}</strong></p>

    <hr>

    <img class="img-responsive" src="http://placehold.it/900x300" />
    <hr>
    <p>{{content.content | truncate }}</p>
    <a class="btn btn-primary" href="#">Read More <span class="glyphicon glyphicon-chevron-right"></span></a>

    <hr />

  </div>
</template>

<script>
  export default {
    name: 'articleDescription',
    data: () => ({}),
    props: ['content'],
    filters: {
      truncate: function (string, val) {
        return string.substring(0, 200) + '...'
      }
    }
  }
</script>
