// angular2/src/app/components/about/about.component.ts
import { Component } from '@angular/core';
@Component({
  selector: 'about',
  templateUrl: './about.component.html',
  styleUrls: ['./about.component.scss']
})
export class AboutComponent {}
<div>
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">About
                <small>It's Nice to Meet You!</small>
            </h1>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <img class="img-responsive" src="http://placehold.it/750x450">
        </div>
        <div class="col-md-6">
            <h2>Welcome to 'Modern Business'</h2>

            <p>This is a great place to introduce your company or project and describe what you do. This about page
                features general company information, employee bios, and other helpful elements.</p>

            <p>Lid est laborum dolo rumes fugats untras. Etharums ser quidem rerum facilis dolores nemis omnis fugats
                vitaes nemo minima rerums unsers sadips amets.. Sed ut perspiciatis unde omnis iste natus error sit
                voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore
                veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia
                voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione
                voluptatem sequi nesciunt.</p>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <h2 class="page-header">Our Team</h2>
        </div>

        <div class="col-sm-4" ng-repeat="t in [1,2,3]">
            <img class="img-responsive" src="http://placehold.it/750x450">

            <h3>John Smith
                <small>Job Title</small>
            </h3>
            <p>What does this team member do? Keep it short! This is also a great spot for social links!</p>
            <ul class="list-unstyled list-inline list-social-icons">
                <li class="tooltip-social facebook-link"><a href="#facebook-profile" data-toggle="tooltip"
                                                            data-placement="top" title="Facebook"><i
                        class="fa fa-facebook-square fa-2x"></i></a>
                </li>
                <li class="tooltip-social linkedin-link"><a href="#linkedin-profile" data-toggle="tooltip"
                                                            data-placement="top" title="LinkedIn"><i
                        class="fa fa-linkedin-square fa-2x"></i></a>
                </li>
                <li class="tooltip-social twitter-link"><a href="#twitter-profile" data-toggle="tooltip"
                                                           data-placement="top" title="Twitter"><i
                        class="fa fa-twitter-square fa-2x"></i></a>
                </li>
                <li class="tooltip-social google-plus-link"><a href="#google-plus-profile" data-toggle="tooltip"
                                                               data-placement="top" title="Google+"><i
                        class="fa fa-google-plus-square fa-2x"></i></a>
                </li>
            </ul>
        </div>
    </div>

    <div class="row">

        <div class="col-lg-12">
            <h2 class="page-header">Our Customers</h2>
        </div>

        <div class="col-md-2 col-sm-4 col-xs-6" ng-repeat="t in [1,2,3,4,5,6]">
            <img class="img-responsive img-customer" src="http://placehold.it/500x300">
        </div>

    </div>

</div>

// vue.js/src/views/About.vue
<template>
  <div>
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header">About
          <small>It's Nice to Meet You!</small>
        </h1>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6">
        <img class="img-responsive" src="http://placehold.it/750x450">
      </div>
      <div class="col-md-6">
        <h2>Welcome to 'Modern Business'</h2>

        <p>This is a great place to introduce your company or project and describe what you do. This about page
          features general company information, employee bios, and other helpful elements.</p>

        <p>Lid est laborum dolo rumes fugats untras. Etharums ser quidem rerum facilis dolores nemis omnis fugats
          vitaes nemo minima rerums unsers sadips amets.. Sed ut perspiciatis unde omnis iste natus error sit
          voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore
          veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia
          voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione
          voluptatem sequi nesciunt.</p>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-12">
        <h2 class="page-header">Our Team</h2>
      </div>

      <div class="col-sm-4" ng-repeat="t in [1,2,3]">
        <img class="img-responsive" src="http://placehold.it/750x450">

        <h3>John Smith
          <small>Job Title</small>
        </h3>
        <p>What does this team member do? Keep it short! This is also a great spot for social links!</p>
        <ul class="list-unstyled list-inline list-social-icons">
          <li class="tooltip-social facebook-link"><a href="#facebook-profile" data-toggle="tooltip"
                                                      data-placement="top" title="Facebook"><i
            class="fa fa-facebook-square fa-2x"></i></a>
          </li>
          <li class="tooltip-social linkedin-link"><a href="#linkedin-profile" data-toggle="tooltip"
                                                      data-placement="top" title="LinkedIn"><i
            class="fa fa-linkedin-square fa-2x"></i></a>
          </li>
          <li class="tooltip-social twitter-link"><a href="#twitter-profile" data-toggle="tooltip"
                                                     data-placement="top" title="Twitter"><i
            class="fa fa-twitter-square fa-2x"></i></a>
          </li>
          <li class="tooltip-social google-plus-link"><a href="#google-plus-profile" data-toggle="tooltip"
                                                         data-placement="top" title="Google+"><i
            class="fa fa-google-plus-square fa-2x"></i></a>
          </li>
        </ul>
      </div>
    </div>

    <!-- Our Customers -->

    <div class="row">

      <div class="col-lg-12">
        <h2 class="page-header">Our Customers</h2>
      </div>

      <div class="col-md-2 col-sm-4 col-xs-6" ng-repeat="t in [1,2,3,4,5,6]">
        <img class="img-responsive img-customer" src="http://placehold.it/500x300">
      </div>

    </div>

  </div>
</template>
